name: cleai_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - pandas=1.5.3
  - numpy=1.24.4
  - scikit-learn=1.2.2
  - pytorch
  - tensorflow=2.10.0
  - pyspark=3.4.1
  - nbformat=5.9.2
  - sqlalchemy=2.0.19
  - great-expectations=0.17.22
  - pydantic=1.10.12
  - streamlit=1.24.1
  - pyjanitor=0.26.0
  - openpyxl=3.1.2
  - xlrd=2.0.1
  - jinja2=3.1.2
  - markupsafe=2.1.3
  - pip=23.2.1
  - transformers
  - pip:
    - "ipython==7.34.0"
    - "dataprep==0.4.0"
    - "ydata-profiling==4.6.0"
    - "tqdm==4.66.1"
    - "importlib-metadata==6.8.0"
    - "typing-extensions==4.8.0"